language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yishensun/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yishensun/react-test npm test

after_success:
  - docker build -t yishensun/multi-client ./client
  - docker build -t yishensun/multi-nginx ./nginx
  - docker build -t yishensun/multi-server ./server
  - docker build -t yishensun/multi-worker ./worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-506805517360"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
